pull_requests:
  do_not_increment_build_number: true
environment:
  repo_token:
    secure: G8LWMoVsA3NzOySM+ZQF4sBsUZzPSE8RDJyrp6QKVKCAuHBMR27eU4+1bvGxhSEk
skip_branch_with_pr: true
image: Visual Studio 2022
configuration:
  - Release
shallow_clone: true
install:
  - choco install doxygen.install
build:
  project: Byond.TopicSender.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
before_build:
  - dotnet restore
after_build:
  - ps: if($env:CONFIGURATION -match "Release") { if($env:APPVEYOR_REPO_BRANCH -match "master"){ $env:NugetDeploy = "Do it." } }
  - ps: Tools/BuildDox.ps1
test_script:
  - ps: $wc = New-Object 'System.Net.WebClient'
deploy:
  - provider: NuGet
    api_key:
      secure: WAvplT2WqZ5skaLjR/cyeWICySN3EfH/Dz2CsvAtoC1TjxwRR+SvPfvp5GG3xy1V
    artifact: /.*(\.|\.s)nupkg/
    on:
      NugetDeploy: "Do it."
