pull_requests:
  do_not_increment_build_number: true
environment:
  repo_token:
    secure: +CbfdKj+vOprqtC5mJp5mwJ92SH+y9eJ/ufXMyrNJGjaXW0fDBLnHmvzfWW73s5/
skip_branch_with_pr: true
image: Visual Studio 2019
configuration:
  - Debug
  - Release
shallow_clone: true
cache:
  - packages -> **\*.csproj
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
install:
  - choco install doxygen.install
build:
  project: Byond.TopicSender.sln
  publish_nuget: true
before_build:
  - dotnet restore
after_build:
  - ps: if($env:CONFIGURATION -match "Release") { if($env:APPVEYOR_REPO_BRANCH -match "master"){ $env:NugetDeploy = "Do it." } }
  - ps: Tools/BuildDox.ps1
deploy:
  - provider: NuGet
    api_key:
      secure: wEJOUfUHOuMcQO3zLNq9nlFVERI8l9PW7QMpQ1wD7o+5XHW8SugsGLlWR+hz1GCm
    artifact: /.*\.nupkg/
    on:
      NugetDeploy: "Do it."
