Byond.TopicSender: Byond.TopicSender.TopicClient Class Reference
Byond.TopicSender.TopicClient Class Reference
Public Member Functions
TopicClient (SocketParameters socketParameters, ILogger? logger=null)
Initializes a new instance of the TopicClient class.
async Task< TopicResponse > SendTopic (string destinationServer, string queryString, ushort port, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a destinationServer .
Parameters
destinationServer The IP address or domain name of the server.
queryString The query string to send.
port The port of the destinationServer .
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
Task< TopicResponse > SendTopic (IPAddress address, string queryString, ushort port, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a server at a given address .
Parameters
address The IPAddress of the server.
queryString The query string to send.
port The port of the address .
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
async Task< TopicResponse > SendTopic (IPEndPoint endPoint, string queryString, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a server at a given endPoint .
Parameters
endPoint The IPEndPoint of the server.
queryString The query string to send.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
string SanitizeString (string input)
Properly escapes characters for a Byond Topic() packet. Performs URL encoding. See http://www.byond.com/docs/ref/info.html#/proc/list2params.
Parameters
input The string to sanitize.
Returns
The sanitized string.
Task< TopicResponse > SendTopic (string destinationServer, string queryString, ushort port, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a destinationServer .
Task< TopicResponse > SendTopic (IPAddress address, string queryString, ushort port, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a server at a given address .
Task< TopicResponse > SendTopic (IPEndPoint endPoint, string queryString, CancellationToken cancellationToken=default)
Send a queryString to the /world/Topic of a server at a given endPoint .
string SanitizeString (string input)
Properly escapes characters for a Byond Topic() packet. Performs URL encoding. See http://www.byond.com/docs/ref/info.html#/proc/list2params.
Private Attributes
readonly SocketParameters socketParameters
The SocketParameters for the TopicClient.
readonly ILogger logger
The ILogger for the TopicClient.
Detailed Description
Definition at line 19 of file TopicClient.cs.
Constructor & Destructor Documentation
TopicClient()
Byond.TopicSender.TopicClient.TopicClient (SocketParameters socketParameters, ILogger? logger = null)
Initializes a new instance of the TopicClient class.
Parameters
socketParameters The SocketParameters to use.
logger The optional ILogger to use.
Definition at line 36 of file TopicClient.cs.
        {
            this.socketParameters = socketParameters ?? throw new ArgumentNullException(nameof(socketParameters));
            this.logger = logger ?? new NullLogger<TopicClient>();
        }
References Byond.TopicSender.TopicClient.logger, and Byond.TopicSender.TopicClient.socketParameters.
Member Function Documentation
SanitizeString()
string Byond.TopicSender.TopicClient.SanitizeString (string input)
Properly escapes characters for a Byond Topic() packet. Performs URL encoding. See http://www.byond.com/docs/ref/info.html#/proc/list2params.
Parameters
input The string to sanitize.
Returns
The sanitized string.
Implements Byond.TopicSender.ITopicClient.
Definition at line 233 of file TopicClient.cs.
        {
            if (input == null)
                throw new ArgumentNullException(nameof(input));
            return HttpUtility.UrlEncode(input);
        }
SendTopic() [1/3]
Task< TopicResponse > Byond.TopicSender.TopicClient.SendTopic (IPAddress address, string queryString, ushort port, CancellationToken cancellationToken = default)
Send a queryString to the /world/Topic of a server at a given address .
Parameters
address The IPAddress of the server.
queryString The query string to send.
port The port of the address .
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
Implements Byond.TopicSender.ITopicClient.
Definition at line 54 of file TopicClient.cs.
        {
            if (address == null)
                throw new ArgumentNullException(nameof(address));
            return SendTopic(new IPEndPoint(address, port), queryString, cancellationToken);
        }
References Byond.TopicSender.TopicClient.SendTopic().
SendTopic() [2/3]
async Task< TopicResponse > Byond.TopicSender.TopicClient.SendTopic (IPEndPoint endPoint, string queryString, CancellationToken cancellationToken = default)
Send a queryString to the /world/Topic of a server at a given endPoint .
Parameters
endPoint The IPEndPoint of the server.
queryString The query string to send.
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
Implements Byond.TopicSender.ITopicClient.
Definition at line 62 of file TopicClient.cs.
        {
            if (endPoint == null)
                throw new ArgumentNullException(nameof(endPoint));
            if (queryString == null)
                throw new ArgumentNullException(nameof(queryString));
            using var socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp);
            {
                // prepare
                var needsQueryToken = queryString.Length == 0 || queryString[0] != '?';
                var queryStringByteLength = Encoding.UTF8.GetByteCount(queryString);
                /* https://discord.com/channels/484170914754330625/484170915253321734/1117238275963367465
                    // this one's big endian!
                    struct byond_msg_frame {
                        short unsigned id;
                        short unsigned len;
                    } __attribute__((packed));
                    struct byond_msg_topic {
                        // if flags isn't 0 then there's more to this struct!
                        char unsigned flags;
                        int unsigned port;
                        char msg[];
                    } __attribute__((packed));
                */
                const int TopicMessageHeaderLength = 1 // flags
                    + 4; // port
                var bytesBeforeString = 2 // id
                    + 2 // length header
                    + TopicMessageHeaderLength;
                if (needsQueryToken)
                    ++bytesBeforeString;
                var totalLength = bytesBeforeString
                    + queryStringByteLength
                    + 1; // null terminator
                var lengthHeader = totalLength - TopicResponseHeader.HeaderLength;
                if (lengthHeader > UInt16.MaxValue)
                    throw new ArgumentOutOfRangeException(nameof(queryString), queryString, "Topic too long!");
                await using var dataStream = new MemoryStream(totalLength);
                await using (var writer = new BinaryWriter(dataStream, Encoding.UTF8, true))
                {
                    writer.Write((byte)0);
                    writer.Write((byte)0x83);
                    // #RIP-lilEndy
                    writer.Write(BinaryPrimitives.ReverseEndianness((ushort)lengthHeader));
                    for (var i = 0; i < TopicMessageHeaderLength; ++i)
                        writer.Write((byte)0);
                    if (needsQueryToken)
                        writer.Write('?');
                    writer.Seek(queryStringByteLength, SeekOrigin.Current);
                    writer.Write((byte)0);
                }
                var sendBuffer = dataStream.GetBuffer();
                Encoding.UTF8.GetBytes(queryString, 0, queryString.Length, sendBuffer, bytesBeforeString);
                // connect
                using var connectCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                connectCts.CancelAfter(socketParameters.ConnectTimeout);
                await socket.ConnectAsync(endPoint, connectCts.Token);
                // send
                using var sendCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                sendCts.CancelAfter(socketParameters.SendTimeout);
                for (int offset = 0, chunkCount = 1; offset < dataStream.Length; ++chunkCount)
                {
                    logger.LogTrace("Send chunk {chunk}, offset {offset}", chunkCount, offset);
                    offset += await socket.SendAsync(
                        new ReadOnlyMemory<byte>(sendBuffer, offset, (int)(dataStream.Length - offset)),
                        SocketFlags.None,
                        sendCts.Token);
                }
            }
            // DO NOT DO THIS, it breaks things
            // socket.Shutdown(SocketShutdown.Send);
            // receive
            var returnedData = new byte[TopicResponseHeader.HeaderLength];
            var receiveOffset = 0;
            try
            {
                TopicResponseHeader? header = null;
                var isWindows = RuntimeInformation.IsOSPlatform(OSPlatform.Windows);
                using var receiveCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                receiveCts.CancelAfter(socketParameters.ReceiveTimeout);
                for (var chunkCount = 1; receiveOffset < returnedData.Length; ++chunkCount)
                {
                    logger.LogTrace("Receive chunk {chunk}, offset {receiveOffset}", chunkCount, receiveOffset);
                    int read;
                    try
                    {
                        read = await socket.ReceiveAsync(
                            new Memory<byte>(returnedData, receiveOffset, returnedData.Length - receiveOffset),
                            isWindows && header == null
                                ? SocketFlags.Partial
                                : SocketFlags.None,
                            receiveCts.Token);
                    }
                    catch (SocketException ex)
                    {
                        // BYOND closes the socket after replying *sometimes*
                        if ((SocketError)ex.ErrorCode == SocketError.ConnectionReset
                            && receiveOffset == returnedData.Length)
{
                            logger.LogDebug(ex, "BYOND reset connection after receive");
                            break;
                        }
                        throw;
                    }
                    receiveOffset += read;
                    if (read == 0)
                    {
                        if (receiveOffset < returnedData.Length)
                            logger.LogDebug("Zero bytes read at offset {receiveOffset} before expected length of {expectedLength}.", receiveOffset, returnedData.Length);
                        break;
                    }
                    if (header == null && receiveOffset >= TopicResponseHeader.HeaderLength)
                    {
                        // we now have the header
                        header = new TopicResponseHeader(returnedData);
                        var expectedLength = header.PacketLength;
                        logger.LogTrace("Header indicates packet length of {expectedLength}", expectedLength);
                        Array.Resize(ref returnedData, expectedLength);
                    }
                }
                if (socket.Connected)
                    try
                    {
                        // we need to properly disconnect the socket, otherwise Byond can be an asshole about future sends
                        logger.LogTrace("Disconnect");
                        using var disconnectCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
                        disconnectCts.CancelAfter(socketParameters.DisconnectTimeout);
                        await socket.DisconnectAsync(false, disconnectCts.Token).ConfigureAwait(false);
                    }
                    catch (Exception ex) when (ex is not OperationCanceledException)
                    {
                        logger.LogDebug(ex, "Disconnect exception!");
                    }
            }
            finally
            {
                if (returnedData.Length > receiveOffset)
                    Array.Resize(ref returnedData, receiveOffset);
            }
            return new TopicResponse(returnedData);
        }
References Byond.TopicSender.SocketParameters.ConnectTimeout, Byond.TopicSender.SocketParameters.DisconnectTimeout, Byond.TopicSender.TopicResponseHeader.HeaderLength, Byond.TopicSender.TopicClient.logger, Byond.TopicSender.TopicResponseHeader.PacketLength, Byond.TopicSender.SocketParameters.ReceiveTimeout, Byond.TopicSender.SocketParameters.SendTimeout, and Byond.TopicSender.TopicClient.socketParameters.
SendTopic() [3/3]
async Task< TopicResponse > Byond.TopicSender.TopicClient.SendTopic (string destinationServer, string queryString, ushort port, CancellationToken cancellationToken = default)
Send a queryString to the /world/Topic of a destinationServer .
Parameters
destinationServer The IP address or domain name of the server.
queryString The query string to send.
port The port of the destinationServer .
cancellationToken The CancellationToken for the operation.
Returns
A Task<TResult> resulting in the returned TopicResponse from the server.
Implements Byond.TopicSender.ITopicClient.
Definition at line 43 of file TopicClient.cs.
        {
            if (destinationServer == null)
                throw new ArgumentNullException(nameof(destinationServer));
            var hostEntries = await Dns.GetHostAddressesAsync(destinationServer, cancellationToken).ConfigureAwait(false);
            // pick the first IPV4 entry
            return await SendTopic(hostEntries.First(x => x.AddressFamily == AddressFamily.InterNetwork), queryString, port, cancellationToken).ConfigureAwait(false);
        }
References Byond.TopicSender.TopicClient.SendTopic().
Referenced by Byond.TopicSender.TopicClient.SendTopic(), and Byond.TopicSender.TopicClient.SendTopic().
Member Data Documentation
logger
readonly ILogger Byond.TopicSender.TopicClient.logger private
The ILogger for the TopicClient.
Definition at line 29 of file TopicClient.cs.
Referenced by Byond.TopicSender.TopicClient.SendTopic(), and Byond.TopicSender.TopicClient.TopicClient().
socketParameters
readonly SocketParameters Byond.TopicSender.TopicClient.socketParameters private
The SocketParameters for the TopicClient.
Definition at line 24 of file TopicClient.cs.
Referenced by Byond.TopicSender.TopicClient.SendTopic(), and Byond.TopicSender.TopicClient.TopicClient().
The documentation for this class was generated from the following file:
Byond.TopicSender/TopicClient.cs