name: 'Nuget Deploy'
on:
  push:
    branches:
    - master

concurrency:
  group: "nuget-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Nuget Package
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[NugetDeploy]')
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Publish Tgstation.Server.Client to NuGet
      uses: alirezanet/publish-nuget@e276c40afeb2a154046f0997820f2a9ea74832d9 # v3.1.0
      with:
        PROJECT_FILE_PATH: Byond.TopicSender/Byond.TopicSender.csproj
        TAG_COMMIT: false
        INCLUDE_SYMBOLS: true
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
